// Complete ICSE and CBSE chapter data for classes 6-12
// Organized by board → subject → class → chapters

export interface ChapterInfo {
  name: string;
  subject: string;
  board: string;
  classNum: number;
}

// ICSE chapters for key subjects — class 9 and 10 (most common)
const ICSE_CHAPTERS: Record<string, Record<number, string[]>> = {
  'Physics': {
    9: [
      'Measurements and Experimentation',
      'Motion in One Dimension',
      'Laws of Motion',
      'Fluids',
      'Heat and Energy',
      'Light',
      'Sound',
      'Electricity and Magnetism',
    ],
    10: [
      'Force, Work, Power and Energy',
      'Machines',
      'Refraction of Light at Plane Surfaces',
      'Refraction through a Lens',
      'Spectrum',
      'Sound',
      'Current Electricity',
      'Household Circuits',
      'Electro-magnetism',
      'Calorimetry',
      'Radioactivity',
    ],
    11: [
      'Units and Measurements',
      'Motion in a Straight Line',
      'Motion in a Plane',
      'Laws of Motion',
      'Work, Energy and Power',
      'System of Particles and Rotational Motion',
      'Gravitation',
      'Mechanical Properties of Solids',
      'Mechanical Properties of Fluids',
      'Thermal Properties of Matter',
      'Thermodynamics',
      'Kinetic Theory',
      'Oscillations',
      'Waves',
    ],
    12: [
      'Electric Charges and Fields',
      'Electrostatic Potential and Capacitance',
      'Current Electricity',
      'Moving Charges and Magnetism',
      'Magnetism and Matter',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Ray Optics and Optical Instruments',
      'Wave Optics',
      'Dual Nature of Radiation and Matter',
      'Atoms',
      'Nuclei',
      'Semiconductor Electronics',
    ],
  },
  'Chemistry': {
    9: [
      'The Language of Chemistry',
      'Chemical Changes and Reactions',
      'Water',
      'Atomic Structure and Chemical Bonding',
      'The Periodic Table',
      'Study of the First Element — Hydrogen',
      'Study of Gas Laws',
      'Atmospheric Pollution',
    ],
    10: [
      'Periodic Properties and Variations of Properties',
      'Chemical Bonding',
      'Acids, Bases and Salts',
      'Analytical Chemistry',
      'Mole Concept and Stoichiometry',
      'Electrolysis',
      'Metallurgy',
      'Study of Compounds',
      'Organic Chemistry',
    ],
    11: [
      'Some Basic Concepts of Chemistry',
      'Structure of Atom',
      'Classification of Elements and Periodicity',
      'Chemical Bonding and Molecular Structure',
      'States of Matter',
      'Thermodynamics',
      'Equilibrium',
      'Redox Reactions',
      'Hydrogen',
      'The s-Block Elements',
      'The p-Block Elements',
      'Organic Chemistry - Basic Principles',
      'Hydrocarbons',
      'Environmental Chemistry',
    ],
    12: [
      'The Solid State',
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'Surface Chemistry',
      'General Principles of Isolation of Elements',
      'The p-Block Elements',
      'The d and f Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols and Ethers',
      'Aldehydes, Ketones and Carboxylic Acids',
      'Amines',
      'Biomolecules',
      'Polymers',
      'Chemistry in Everyday Life',
    ],
  },
  'Mathematics': {
    9: [
      'Rational and Irrational Numbers',
      'Compound Interest',
      'Expansions',
      'Factorisation',
      'Simultaneous Linear Equations',
      'Indices and Exponents',
      'Logarithms',
      'Triangles',
      'Mid-point and Intercept Theorems',
      'Pythagoras Theorem',
      'Rectilinear Figures',
      'Construction of Polygons',
      'Area and Perimeter of Plane Figures',
      'Statistics',
      'Mean and Median',
      'Coordinate Geometry',
      'Trigonometric Ratios',
    ],
    10: [
      'Goods and Services Tax',
      'Banking',
      'Shares and Dividends',
      'Linear Inequations',
      'Quadratic Equations',
      'Ratio and Proportion',
      'Factorisation',
      'Matrices',
      'Arithmetic Progression',
      'Geometric Progression',
      'Coordinate Geometry',
      'Similarity',
      'Loci',
      'Circles',
      'Constructions',
      'Measures of Central Tendency',
      'Probability',
      'Trigonometric Identities',
      'Heights and Distances',
      'Mensuration',
    ],
    11: [
      'Sets',
      'Relations and Functions',
      'Trigonometric Functions',
      'Principle of Mathematical Induction',
      'Complex Numbers and Quadratic Equations',
      'Linear Inequalities',
      'Permutations and Combinations',
      'Binomial Theorem',
      'Sequences and Series',
      'Straight Lines',
      'Conic Sections',
      'Introduction to Three Dimensional Geometry',
      'Limits and Derivatives',
      'Mathematical Reasoning',
      'Statistics',
      'Probability',
    ],
    12: [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices',
      'Determinants',
      'Continuity and Differentiability',
      'Application of Derivatives',
      'Integrals',
      'Application of Integrals',
      'Differential Equations',
      'Vector Algebra',
      'Three Dimensional Geometry',
      'Linear Programming',
      'Probability',
    ],
  },
  'Biology': {
    9: [
      'Introducing Biology',
      'Cell: The Unit of Life',
      'Tissues: Plant and Animal Tissues',
      'The Flower',
      'Pollination and Fertilization',
      'Seeds: Structure and Germination',
      'Respiration in Plants',
      'Five Kingdom Classification',
      'Economic Importance of Bacteria and Fungi',
      'Nutrition',
      'Digestive System',
      'Movement and Locomotion',
      'Skin: The Jack of All Trades',
    ],
    10: [
      'Cell Cycle and Cell Division',
      'Genetics — Some Basic Fundamentals',
      'Absorption by Roots',
      'Transpiration',
      'Photosynthesis',
      'Chemical Coordination in Plants',
      'The Circulatory System',
      'The Excretory System',
      'The Nervous System',
      'The Endocrine System',
      'The Reproductive System',
      'Population',
      'Human Evolution',
      'Pollution',
    ],
    11: [
      'The Living World',
      'Biological Classification',
      'Plant Kingdom',
      'Animal Kingdom',
      'Morphology of Flowering Plants',
      'Anatomy of Flowering Plants',
      'Structural Organisation in Animals',
      'Cell: The Unit of Life',
      'Biomolecules',
      'Cell Cycle and Cell Division',
      'Transport in Plants',
      'Mineral Nutrition',
      'Photosynthesis in Higher Plants',
      'Respiration in Plants',
      'Plant Growth and Development',
      'Digestion and Absorption',
      'Breathing and Exchange of Gases',
      'Body Fluids and Circulation',
      'Excretory Products and their Elimination',
      'Locomotion and Movement',
      'Neural Control and Coordination',
      'Chemical Coordination and Integration',
    ],
    12: [
      'Reproduction in Organisms',
      'Sexual Reproduction in Flowering Plants',
      'Human Reproduction',
      'Reproductive Health',
      'Principles of Inheritance and Variation',
      'Molecular Basis of Inheritance',
      'Evolution',
      'Human Health and Disease',
      'Strategies for Enhancement in Food Production',
      'Microbes in Human Welfare',
      'Biotechnology: Principles and Processes',
      'Biotechnology and its Applications',
      'Organisms and Populations',
      'Ecosystem',
      'Biodiversity and Conservation',
      'Environmental Issues',
    ],
  },
  'Computer Applications': {
    9: [
      'Introduction to Object Oriented Programming',
      'Elementary Concepts of Objects and Classes',
      'Values and Data Types',
      'Operators in Java',
      'Input in Java',
      'Conditional Constructs in Java',
      'Iterative Constructs in Java',
      'Nested for Loops',
      'String Handling',
      'Mathematical Library Methods',
    ],
    10: [
      'Revision of Class 9',
      'Class as the Basis of all Computation',
      'User-Defined Methods',
      'Constructors',
      'Library Classes',
      'Encapsulation',
      'Arrays — Single Dimensional',
      'Arrays — Double Dimensional',
      'String Handling',
    ],
    11: [
      'Computer Fundamentals',
      'Data Representation',
      'Boolean Algebra',
      'Introduction to Programming',
      'Programming Methodology',
      'Arrays',
      'Strings',
      'Functions',
    ],
    12: [
      'Boolean Algebra',
      'Communication and Network Concepts',
      'Data Structures',
      'Databases and SQL',
      'Object Oriented Programming',
      'Inheritance',
      'Computational Thinking',
    ],
  },
  'History & Civics': {
    9: [
      'The Harappan Civilization',
      'The Vedic Period',
      'Jainism and Buddhism',
      'The Mauryan Empire',
      'The Age of the Guptas',
      'The Delhi Sultanate',
      'The Mughal Empire',
      'The Composite Culture',
      'Our Parliament',
      'Elections',
      'The Union Government',
      'The Judiciary',
    ],
    10: [
      'The First War of Independence 1857',
      'Growth of Nationalism',
      'First Phase of the Indian National Movement',
      'Second Phase of the Indian National Movement',
      'The World Wars',
      'Rise of Dictatorships',
      'The United Nations',
      'Universal Declaration of Human Rights',
      'The Union Legislature',
      'The Union Executive',
      'The Judiciary',
    ],
    11: [
      'Introduction to History',
      'Early Societies',
      'Early Cities',
      'An Empire Across Three Continents',
      'Nomadic Empires',
      'Three Orders',
      'Changing Cultural Traditions',
      'Confrontation of Cultures',
      'Industrial Revolution',
      'Displacing Indigenous Peoples',
      'Paths to Modernisation',
    ],
    12: [
      'Bricks, Beads and Bones',
      'Kings, Farmers and Towns',
      'Kinship, Caste and Class',
      'Thinkers, Beliefs and Buildings',
      'Through the Eyes of Travellers',
      'Bhakti-Sufi Traditions',
      'An Imperial Capital: Vijayanagara',
      'Peasants, Zamindars and the State',
      'Colonialism and the Countryside',
      'Rebels and the Raj',
      'Mahatma Gandhi and the National Movement',
      'Framing the Constitution',
    ],
  },
  'English': {
    9: [
      'Reading Comprehension',
      'Writing Skills — Essay',
      'Writing Skills — Letter',
      'Writing Skills — Notice and Email',
      'Grammar — Tenses',
      'Grammar — Active and Passive Voice',
      'Grammar — Direct and Indirect Speech',
      'Grammar — Prepositions and Conjunctions',
      'Literature — Poetry Analysis',
      'Literature — Prose Analysis',
      'Literature — Drama Study',
    ],
    10: [
      'Reading Comprehension',
      'Writing Skills — Composition',
      'Writing Skills — Letter Writing',
      'Writing Skills — Notice, Email, Report',
      'Grammar — Sentence Transformation',
      'Grammar — Tenses and Voice',
      'Grammar — Direct Indirect Speech',
      'Grammar — Punctuation and Vocabulary',
      'Literature — Poetry',
      'Literature — Short Stories',
      'Literature — Drama',
    ],
    11: [
      'Reading Comprehension — Advanced',
      'Writing Skills — Article and Report',
      'Writing Skills — Speech and Debate',
      'Grammar — Advanced Sentence Structures',
      'Literature — Poetry Analysis',
      'Literature — Novel Study',
      'Literature — Drama Study',
    ],
    12: [
      'Reading Comprehension — Advanced',
      'Writing Skills — Article, Report, Letter',
      'Writing Skills — Speech, Debate, Creative Writing',
      'Grammar — Sentence Transformation Advanced',
      'Literature — Poetry',
      'Literature — Novel',
      'Literature — Drama',
      'Literature — Non-fiction',
    ],
  },
  'Geography': {
    9: [
      'Earth as a Planet',
      'Geographic Grid — Latitudes and Longitudes',
      'Rotation and Revolution',
      'Structure of the Earth',
      'Volcanism',
      'Earthquakes',
      'Weathering',
      'River',
      'Weather and Climate',
      'Natural Regions of the World',
      'Map Work',
    ],
    10: [
      'Map Reading and Interpretation',
      'Climate of India',
      'Soil Resources of India',
      'Natural Vegetation of India',
      'Water Resources of India',
      'Mineral and Energy Resources',
      'Agriculture in India',
      'Manufacturing Industries',
      'Transport in India',
      'Waste Management',
    ],
    11: [
      'Geography as a Discipline',
      'The Origin and Evolution of the Earth',
      'Interior of the Earth',
      'Distribution of Oceans and Continents',
      'Minerals and Rocks',
      'Geomorphic Processes',
      'Landforms and their Evolution',
      'Composition and Structure of Atmosphere',
      'Solar Radiation, Heat Balance and Temperature',
      'Atmospheric Circulation and Weather Systems',
      'Water in the Atmosphere',
      'World Climate and Climate Change',
      'Water (Oceans)',
      'Movements of Ocean Water',
      'Life on the Earth',
    ],
    12: [
      'Human Geography: Nature and Scope',
      'The World Population',
      'Population Composition',
      'Human Development',
      'Primary Activities',
      'Secondary Activities',
      'Tertiary and Quaternary Activities',
      'Transport and Communication',
      'International Trade',
      'Human Settlements',
    ],
  },
};

// CBSE uses same structure (largely overlapping with ICSE for classes 11-12)
const CBSE_CHAPTERS = { ...ICSE_CHAPTERS };

export const getChaptersForSubject = (
  subject: string,
  board: string,
  classNum: number
): string[] => {
  const chapters = board === 'CBSE' ? CBSE_CHAPTERS : ICSE_CHAPTERS;
  return chapters[subject]?.[classNum] ?? [];
};

export const getAllChapters = (
  board: string,
  classNum: number
): ChapterInfo[] => {
  const chapters = board === 'CBSE' ? CBSE_CHAPTERS : ICSE_CHAPTERS;
  const result: ChapterInfo[] = [];
  for (const subject of Object.keys(chapters)) {
    const subjectChapters = chapters[subject]?.[classNum] ?? [];
    for (const name of subjectChapters) {
      result.push({ name, subject, board, classNum });
    }
  }
  return result;
};
